### ISSUE TITLE
手机上APP显示已经停止使用

### ISSUE THREAD

**Issue by YUAN-YANG007** [yexxx/TrashClassify_android_app#1]
你好，我用您的app时。下载到手机后显示已经停止运行。
是什么问题呢
![3DK4PICT{$6WC3H$X946VJD](https://user-images.githubusercontent.com/62058663/77421625-20a91600-6e07-11ea-8757-6cc942242e03.png)

**Comment by yexxx** [comment]
请使用安卓7.0及以上版本试试

在 2020年3月24日星期二，YUAN-YANG007 <notifications@github.com> 写道：

**Comment by majunqing** [comment]
我的哪个App



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "YUAN-YANG007"; 
发送时间: 2020年3月24日(星期二) 晚上7:39
收件人: "yexxx/TrashClassify_android_app";
抄送: "Subscribed";
主题: [yexxx/TrashClassify_android_app] 手机上APP显示已经停止使用 (#1)





 
你好，我用您的app时。下载到手机后显示已经停止运行。
 是什么问题呢
 
 
&mdash;

**Comment by Lqingian** [comment]
想问您一下，app运行时连接不上网络是什么原因呢？
登陆注册那儿  baseURL   IP地址写的是什么？
